### ISSUE TITLE
sketch is not defined

### ISSUE THREAD

**Issue by konsumer** [BohemianCoding/SketchAPI#218]
I get this error:

```
/Users/konsumer/Desktop/data-locations/node_modules/sketch-api/exposed-npm-package.js:9
module.exports = sketch
                 ^

ReferenceError: sketch is not defined
    at Object.<anonymous> (/Users/konsumer/Desktop/data-locations/node_modules/sketch-api/exposed-npm-package.js:9:18)
    at Module._compile (internal/modules/cjs/loader.js:702:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:713:10)
    at Module.load (internal/modules/cjs/loader.js:612:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:551:12)
    at Function.Module._load (internal/modules/cjs/loader.js:543:3)
    at Module.require (internal/modules/cjs/loader.js:650:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/Users/konsumer/Desktop/data-locations/index.js:1:78)
    at Module._compile (internal/modules/cjs/loader.js:702:30)
```

from this code:

```
const api = require('sketch-api')
console.log(api)
```

**Comment by konsumer** [comment]
Oh I see, I need to make a plugin with this, I can't just arbiltrarilly hook into the running sketch window.

**Comment by mathieudutour** [comment]
indeed, it's not an npm module, more like a core nodejs module that is provided by sketch. You can `var sketch = require('sketch')` without installing any npm module. It does work in the "run plugin" panel as well

**Comment by konsumer** [comment]
Yep, totally figured it out by downloading the hello-world example plugin, and scripted a solution to my problem in like 5 minutes. Great lib!
