### ISSUE TITLE
Cannot find sketch model 

### ISSUE THREAD

**Issue by IordanisPaschalidis** [BohemianCoding/SketchAPI#243]
Hi I have start playing with sketch api and I tried to create a sketch object but I am getting an error. I have sketch install on my machine but I havent done any other installation because in the README.md it says "The API comes bundled inside Sketch, so no installation is required."  

for example if I try to do the following

`var api = require('sketch')`

I am getting the following error:

Iordaniss-MBP:Desktop uijoker$ node sketch.js
```
module.js:549
    throw err;
    ^

Error: Cannot find module 'sketch'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/uijoker/Desktop/sketch.js:1:73)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
```
I am sure I am missing something - would love if somebody could point me to the correct direction

**Comment by mathieudutour** [comment]
hum this needs to run in Sketch, not in nodejs.

Have a look here: https://developer.sketchapp.com/guides/first-plugin/
